In [2]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'/Users/michelle/Documents/Ironhack/Amsterdam_Project/ProjectAmsterdam'

In [10]:
social_media_by_parties = pd.read_csv('Use Social Media by parties.csv', sep=';')

pd.DataFrame(social_media_by_parties)

social_media_by_parties.head()

media_parties = social_media_by_parties.transpose()

media_parties

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
Use of Social Media By Political Parties,D66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Years,NaN,2007,2008,2009,2010,2011,2012,2013,2014,2015,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Twitter,NaN,NaN,NaN,yes,yes,yes,yes,yes,yes,yes,...,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes
Facebook,NaN,NaN,NaN,yes,yes,yes,yes,yes,yes,yes,...,NaN,yes,yes,yes,yes,yes,yes,yes,yes,yes
Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,...,NaN,NaN,NaN,NaN,NaN,yes,yes,yes,yes,yes
LinkedIn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
media_parties = media_parties.replace(np.nan, ' ', regex=True)

media_parties

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
Use of Social Media By Political Parties,D66,,,,,,,,,,...,,,,,,,,,,
Years,,2007,2008,2009,2010,2011,2012,2013,2014,2015,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Twitter,,,,yes,yes,yes,yes,yes,yes,yes,...,yes,yes,yes,yes,yes,yes,yes,yes,yes,yes
Facebook,,,,yes,yes,yes,yes,yes,yes,yes,...,,yes,yes,yes,yes,yes,yes,yes,yes,yes
Instagram,,,,,,,,,yes,yes,...,,,,,,yes,yes,yes,yes,yes
LinkedIn,,,,,,,,,,,...,,,,,,,,,,

In [14]:
media_parties_num = media_parties.eq('yes').mul(1)

media_parties_num.head()

,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
Use of Social Media By Political Parties,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Years,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Twitter,0,0,0,0,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Facebook,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
Instagram,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,1,1,1,1,1

In [18]:
media_parties_num.sum(axis=1)


media_parties_num.loc['Total'] = media_parties_num[0:12].sum()

0     0
1     0
2     0
3     2
4     4
5     4
6     4
7     4
8     6
9     6
10    6
11    6
12    6
13    0
14    0
15    2
16    2
17    2
18    4
19    4
20    4
21    6
22    6
23    6
24    6
25    6
26    6
27    0
28    0
29    2
     ..
53    6
54    6
55    0
56    0
57    0
58    4
59    4
60    4
61    4
62    4
63    4
64    6
65    6
66    6
67    6
68    6
69    0
70    0
71    0
72    0
73    2
74    4
75    4
76    4
77    4
78    6
79    6
80    6
81    6
82    6
Name: Total, Length: 83, dtype: object